# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F7DCDB
background         #131218
cursor             #827888

active_tab_foreground     #131218
active_tab_background     #F7DCDB
inactive_tab_foreground   #F7DCDB
inactive_tab_background   #131218

active_border_color   #F7DCDB
inactive_border_color #131218
bell_border_color     #414559

color0      #3D3C44
color1		#414559
color2		#414559
color3		#5D638F
color4		#8F6E86
color5		#5B86A4
color6		#AF7572
color7		#ECC5C3
color8		#A58A88
color9		#444863
color10		#444863
color11		#6A71AB
color12		#A27294
color13		#488FBF
color14		#E99C98
color15		#ECC5C3
