# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FCA8A6
background         #160E0D
cursor             #955554

active_tab_foreground     #160E0D
active_tab_background     #FCA8A6
inactive_tab_foreground   #FCA8A6
inactive_tab_background   #160E0D

active_border_color   #FCA8A6
inactive_border_color #160E0D
bell_border_color     #543B3A

color0      #423838
color1		#543B3A
color2		#543B3A
color3		#543B3A
color4		#9D3B3B
color5		#9D3B3B
color6		#C93D3A
color7		#F37A77
color8		#AA5554
color9		#5D3C3A
color10		#5D3C3A
color11		#5D3C3A
color12		#BE3B3B
color13		#BE3B3B
color14		#F70501
color15		#F37A77
