## === Ruta de base de datos y claves ===
# db_path = "~/.local/share/atuin/history.db"
# key_path = "~/.local/share/atuin/key"
# session_path = "~/.local/share/atuin/session"

## === Formato de fecha y zona horaria ===
dialect = "uk"                     # formato de fecha: dd/mm/yyyy
timezone = "local"                # usar zona horaria local

## === Sincronización y actualizaciones ===
auto_sync = true                  # sincronizar automáticamente
update_check = true               # buscar actualizaciones
sync_address = "https://api.atuin.sh"
sync_frequency = "5m"             # sincronizar cada 5 minutos

## === Interfaz de búsqueda ===
search_mode = "fuzzy"             # búsqueda difusa, muy flexible
filter_mode = "workspace"         # filtrar por proyecto/repositorio
workspaces = true                 # habilitar detección de workspace

## Diferente comportamiento para la flecha ↑
filter_mode_shell_up_key_binding = "workspace"
search_mode_shell_up_key_binding = "fuzzy"

## === Estilo de UI ===
style = "compact"
inline_height = 15
inline_height_shell_up_key_binding = 10
invert = true
show_preview = true
show_help = false
show_tabs = true
auto_hide_height = 6

## === Historial ===
enter_accept = true               # enter ejecuta comando (útil si usás `atuin search`)
command_chaining = true           # mantener lógica al usar `&&` o `||`
history_format = "{time}\t{command}\t{duration}"

## Filtrar comandos que no querés guardar
history_filter = [
  "^pass",
  "secret",
  "token",
  "key",
  "aws_access_key",
  "aws_secret_access_key"
]

cwd_filter = [
  "^/tmp",
  "^/var/tmp"
]

## Protecciones contra exposición de secretos
secrets_filter = true

## === Teclas y navegación ===
[keys]
scroll_exits = false
exit_past_line_start = true
accept_past_line_end = true

## === Sincronización v2 ===
[sync]
records = true

## === Vista previa ===
[preview]
strategy = "auto"
max_preview_height = 6

## === Daemon ===
[daemon]
enabled = false
# sync_frequency = 300

## === Stats ===
[stats]
common_subcommands = [
  "git", "npm", "pnpm", "yarn", "docker", "kubectl", "nix", "systemctl",
  "pacman", "paru", "yay", "brew", "cargo", "go", "tmux"
]
common_prefix = ["sudo"]
ignored_commands = ["cd", "ls", "clear"]

## === Búsqueda avanzada ===
[search]
filters = ["workspace", "directory", "session", "host", "global"]
